export interface StartupIdea {
  name: string;
  tagline: string;
  tweet: string;
  _source?: 'openai' | 'fallback';
  _reason?: string;
}

export async function generateStartupIdea(): Promise<StartupIdea> {
  try {
    // Add a cache-busting parameter to prevent caching
    const timestamp = new Date().getTime();
    const response = await fetch('/api/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'
      },
      // Add an empty body to ensure it's a proper POST request
      body: JSON.stringify({}),
    });

    if (!response.ok) {
      console.error(`API request failed with status ${response.status}`);
      throw new Error(`API request failed with status ${response.status}`);
    }

    const data = await response.json();
    
    // Validate the response has the expected structure
    if (!data.name || !data.tagline || !data.tweet) {
      console.error("Invalid response format:", data);
      throw new Error("Invalid response format from API");
    }
    
    return data as StartupIdea;
  } catch (error) {
    console.error("Error generating startup idea:", error);
    
    // Fallback to a default idea if the API call fails
    return {
      name: "FallbackAI",
      tagline: "AI that generates backup plans when APIs fail.",
      tweet: "Just discovered FallbackAI – it creates instant backup plans when APIs fail. Never be caught without a Plan B again! 🛡️🤖 Try it yourself: vibeship.ai @VibeShipAI"
    };
  }
}

// Fallback ideas for when the API is not available
export const fallbackIdeas: StartupIdea[] = [
  {
    name: "DreamDecode AI",
    tagline: "AI that turns your dreams into actionable business strategies.",
    tweet: "AI just created this startup for me: DreamDecode AI – turns your dreams into actionable business strategies overnight. My subconscious is now my business partner! 💤💰 Try it: vibeship.ai @VibeShipAI"
  },
  {
    name: "EchoLearn",
    tagline: "AI that learns your communication style and responds to emails for you.",
    tweet: "Just discovered EchoLearn – AI that learns your communication style and handles all your emails. My inbox has never been emptier! Who's ready for inbox zero? 📨✅ Generated by @VibeShipAI – Try it: vibeship.ai"
  },
  {
    name: "MemoryMesh",
    tagline: "AI that remembers everything you've ever read and recalls it when you need it.",
    tweet: "AI just built this for me: MemoryMesh – never forget anything you've read again. It's like having a photographic memory on demand! 🧠📚 Who's investing? Generated by @VibeShipAI – Try it: vibeship.ai"
  }
]; 